login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.iniciar_sesion, name='iniciar_sesion'),
    path('cerrar', views.cerrar_sesion, name='cerrar_sesion'),
]

scatuaz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trabajador/', include('trabajador.urls')),
    path('usuario/', include('usuario.urls')),
    path('', include('login.urls')),
]

usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_usuario, name='lista_usuario'),
    path('<int:id>', views.ver_usuario, name='ver_usuario'),
    path('agregar', views.agregar_usuario, name='agregar_usuario'),
    path('eliminar/<int:id>', views.eliminar_usuario, name='eliminar_usuario'),
    path(
        'modificar/<int:id>',
        views.modificar_usuario,
        name='modificar_usuario'),
    path(
        'cambiar/<int:id>',
        views.cambiar_contrasena,
        name='cambiar_contrasena'),
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserSCATUAZ(AbstractUser):

    materno = models.CharField(
        max_length=50,
    )

    def __str__(self):
        return str(self.first_name + ' ' + self.last_name)

trabajador/forms.py
from .models import Trabajador, OPCIONES_SEXO, OPCIONES_ESTUDIOS
from django import forms


class TrabajadorForm(forms.ModelForm):
    # DATOS PERSONALES
    paterno = forms.CharField(
        required=True,
        label='Apellido Paterno',
        error_messages={
            'required': 'El campo Apellido Paterno es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    materno = forms.CharField(
        required=True,
        label='Apellido Materno',
        error_messages={
            'required': 'El campo Apellido Materno es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    nombre = forms.CharField(
        required=True,
        label='Nombre',
        max_length=50,
        error_messages={
            'required': 'El campo Nombre es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    rfc = forms.CharField(
        required=True,
        label='RFC',
        max_length=13,
        error_messages={
            'required': 'El campo RFC es obligatorio',
            'max_length': 'La longitud maxima es de 13 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    curp = forms.CharField(
        required=True,
        label='CURP',
        max_length=18,
        min_length=18,
        error_messages={
            'required': 'El campo CURP es obligatorio',
            'min_length': 'La longitud debe ser de 18 caracteres',
            'max_length': 'La longitud debe ser de 18 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    sexo = forms.ChoiceField(
        required=True,
        label='Sexo',
        choices=OPCIONES_SEXO,
        error_messages={
            'required': 'El campo Sexo es obligatorio',
        },
        widget=forms.RadioSelect(
            attrs={'class': 'form-check-input'},
        )
    )
    pais_residencia = forms.CharField(
        required=True,
        label='País de Residencia',
        error_messages={
            'required': 'El campo País de Residencia es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    estado_residencia = forms.CharField(
        required=True,
        label='Estado de Residencia',
        error_messages={
            'required': 'El campo Estado de Residencia es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    municipio_residencia = forms.CharField(
        required=True,
        label='Municipio de Residencia',
        error_messages={
            'required': 'El campo Municipio de Residencia es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    calle = forms.CharField(
        required=True,
        label='Calle de Residencia',
        error_messages={
            'required': 'El campo Calle de Residencia es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    numero = forms.CharField(
        required=True,
        label='Numero',
        error_messages={
            'required': 'El campo Numero es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    colonia = forms.CharField(
        required=True,
        label='Colonia de Residencia',
        error_messages={
            'required': 'El campo Colonia de Residencia es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    cp = forms.CharField(
        required=True,
        label='CP',
        error_messages={
            'required': 'El campo CP es obligatorio',
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    telefono = forms.CharField(
        required=False,
        max_length=10,
        min_length=7,
        label='Teléfono',
        error_messages={
            'required': 'El campo Teléfono es obligatorio',
            'min_length': 'La longitud minima es de 7 caracteres',
            'max_length': 'La longitud maxima es de 10 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    email = forms.CharField(
        required=False,
        label='Correo Electrónico',
        widget=forms.EmailInput(
            attrs={'class': 'form-control'}
        )
    )
    # DATOS LABORALES
    matricula_administrativo = forms.CharField(
        required=True,
        max_length=6,
        label='Matricula de Administrativo',
        error_messages={
            'required': 'El campo Matricula de Administrativo es obligatorio',
            'max_length': 'La longitud maxima es de 6 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    matricula_gremial = forms.CharField(
        required=True,
        max_length=6,
        label='Matricula Gremial',
        error_messages={
            'required': 'El campo Matricula Gremial es obligatorio',
            'max_length': 'La longitud maxima es de 6 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    # DATOS ACADEMICOS
    grado_max_estudios = forms.ChoiceField(
        required=True,
        label='Grado Max de Estudios',
        choices=OPCIONES_ESTUDIOS,
        error_messages={
            'required': 'El campo Grado Max de Estudios es obligatorio',
        },
        widget=forms.Select(
            attrs={'class': 'form-control'},
        )
    )
    # DATOS ISSSTE
    nss = forms.CharField(
        required=False,
        max_length=11,
        label='NSS',
        error_messages={
            'max_length': 'La longitud maxima es de 11 caracteres'
        },
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    no_issste = forms.CharField(
        required=False,
        label='No. de ISSSTE',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    # REGISTROS
    validado_renapo = forms.BooleanField(
        required=False,
        label='Validado por RENAPO',
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input'}
        )
    )
    validado_siri = forms.BooleanField(
        required=False,
        label='Validado por SIRI',
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input', }
        )
    )

    class Meta:
        model = Trabajador
        exclude = ('alta_usuario',)

usuario/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, SetPasswordForm)
from .models import UserSCATUAZ


class UsuarioForm(UserCreationForm):

    first_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el nombre(s)',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Nombre(s) es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Nombre(s)"
    )

    last_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el apellido paterno',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Apellido Paterno es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Apellido Paterno"
    )

    materno = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el apellido materno',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'max_length': 'La longitud maxima es de 50',
        },
        label="Apellido Materno"
    )

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        max_length=50,
        required=False,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo Electrónico es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Correo Electrónico"
    )

    password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Escribe la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Contraseña"
    )

    password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repite la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita contraseña"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = UserSCATUAZ
        fields = ['first_name', 'last_name', 'materno',
                  'username', 'email', 'password1',
                  'password2', 'is_superuser']

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'Las contraseñas no coinciden',
                code='password_mismatch',
            )
        return password2


class CambiarContrasenaForm(SetPasswordForm):

    new_password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Nueva Contraseña"
    )

    new_password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita Nueva contraseña"
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user


class ModificarUsuarioForm(UserChangeForm):

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo Electrónico es obligatorio',
        },
        label="Correo Electrónico"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = UserSCATUAZ
        fields = ['username', 'email', 'is_superuser']

    def save(self, commit=True):
        user = super(ModificarUsuarioForm, self).save(commit=False)
        if commit:
            user.save()
        return user

usuario/templates/agregar_usuario.html
{% extends 'base.html' %}

{% block contenido %}

<form method="post" class="form pt-3">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <ul class = 'form-errors list-unstyled'>
            {% for error in form.non_field_errors %}
                <li class = "text-danger"> {{error}} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-md-6">

            <div class="row mb-2">
                <div class="col">
                    <h1 class="card-title mb-0">Nuevo Usuario</h1>
                    <p class="text-info">Todos los campos con asterisco son obligatorio</p>
                </div>
            </div>

            <div class="card bg-dark text-white mb-3 shadow">
                <div class="card-header mb-3">
                    <h4 class="card-title mb-0">Datos del Nuevo Usuario</h4>
                </div>
                <div class="card-body pb-0">
                    
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_nombres">
                                *{{form.first_name.label}}
                            </label>
                            {{form.first_name}}
                            {% for error in form.first_name.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                *{{form.last_name.label}}
                            </label>
                            {{form.last_name}}
                            {% for error in form.last_name.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_materno">
                                *{{form.materno.label}}
                            </label>
                            {{form.materno}}
                            {% for error in form.materno.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_username">
                                *{{form.username.label}}
                            </label>
                            {{form.username}}
                            {% for error in form.username.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_email">
                                {{form.email.label}}
                            </label>
                            {{form.email}}
                            {% for error in form.email.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_password1">
                                *{{form.password1.label}}
                            </label>
                            {{form.password1}}
                            {% for error in form.password1.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_password2">
                                *{{form.password2.label}}
                            </label>
                            {{form.password2}}
                            {% for error in form.password2.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="col-11">
                            <div class="form-inline justify-content-center mb-3 mt-1">
                                {{form.is_superuser}}
                                <label class="form-check-label" for="id_is_superuser">
                                    {{form.is_superuser.label}}
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row-reverse mb-3 mr-3 mt-2">
                    <a href="{% url "lista_usuario" %}" class="btn btn-secondary ml-2 border">Cancelar</a>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </div>
        </div>
    </div>

</form>

{% endblock contenido %}

usuario/templates/cambiar_contrasena.html
{% extends 'base.html' %}

{% block contenido %}

        <form method="post" class="form pt-4">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-5">

                    <div class="row">
                        <div class="col">
                            <h1 class="card-title">Cambiar Contraseña</h1>
                        </div>
                    </div>
        
        
                    <div class="card mb-3 shadow">
                            <div class="card-header">
                                    <h4 class="card-title mb-0">Datos</h4>
                                </div>
                        <div class="card-body">
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_new_password1">
                                        {{form.new_password1.label}}
                                    </label>
                                    {{form.new_password1}}
                                    {% for error in form.new_password1.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_new_password2">
                                        {{form.new_password2.label}}
                                    </label>
                                    {{form.new_password2}}
                                    {% for error in form.new_password2.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
        
                    <div class="d-flex flex-row-reverse">
                        <a href="{% url "modificar_usuario" usuario.id %}" class="btn btn-secondary ml-2">Cancelar</a>
                        <button type="submit" class="btn btn-primary">Actualizar</button>
                    </div>
                </div>
            </div>

        </form>

{% endblock contenido %}

usuario/templates/confirm_delete_user.html
{% extends 'base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="card col-6 space shadow">
        <div class="card-body">
            <div class="text-center">
                {% if user.get_username == usuario.username %}
                    <h3 class="resaltar text-center d-inline-block mb-4">
                        ¡CUIDADO! Estas por borrar tu propia cuenta
                    </h3>
                {% endif %}
                <h3 class="text-center d-inline">
                    ¿Seguro que deseas eliminar al usuario 
                </h3>
                <h3 class="resaltar text-center d-inline-block">
                    {{ usuario.username }}
                </h3>
                <h3 class="text-center d-inline">
                    ?
                </h3>
            </div>
            <form method="post" class="form">
                {% csrf_token %}
                <div class="d-flex justify-content-end pt-4">
                    <input type="submit" value="Eliminar" class="btn btn-danger mr-2">
                    <a href="{% url 'lista_usuario' %}" class="btn btn-secondary">Regresar</a>
                    
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}
    

usuario/templates/ver_usuario.html
{% extends 'base.html' %} {% block contenido %}

    <div class="row justify-content-center pt-4">
        <div class="col-6">

            <div class="row">                
                <div class="col">
                    <h1 class="card-title">{{usuario.first_name}} {{usuario.last_name}}
                    {{usuario.materno}}</h1>
                </div>
            </div>

            <div class="card text-white bg-dark mb-3 shadow">
                <div class="card-header">
                    <h4 class="card-title mb-0">Datos del usuario</h4>
                </div>
                <div class="card-body pb-0">
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_first_name">
                                Nombre(s)
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.first_name}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                Apellido Paterno
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.last_name}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_materno">
                                Apellido Materno
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.materno}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_usuario">
                                Usuario
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.username}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_correo">
                                Correo Electrónico
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.email}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                ¿Es administrador?
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{% if usuario.is_superuser %}Si{% else %}No{% endif %}"
                            />
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row-reverse mr-3 mb-3 mt-2">
                    <button
                        onClick="javascript:history.go(-1);"
                        class="btn btn-secondary ml-2 border"
                    >
                        Regresar
                    </button>
                    <a href="{% url "eliminar_usuario" usuario.id %}" class="btn btn-danger ml-2">Eliminar</a>
                    <a href="{% url "modificar_usuario" usuario.id %}" class="btn btn-primary">Editar</a>
                </div>
            </div>

        </div>
    </div>


{% endblock contenido %}